### ISSUE TITLE
Region 2: Implement and Test Basic Equations

### ISSUE THREAD

**Issue by beachasaurus-rex** [jonathan-rizk/WaterThermodynamicProperties#2]
Implement the basic equations for region 2 based on the attached document.

The section for region 2 starts at the bottom of page 12.

[IF97-Rev.pdf](https://github.com/jonathan-rizk/WaterThermodynamicProperties/files/3194555/IF97-Rev.pdf)

**Comment by jonathan-rizk** [comment]
Implemented and tested in #1

**Comment by beachasaurus-rex** [comment]
Implemented and tested in #1
